#!/usr/bin/env python3

import requests

# Dataverse parameters
DATAVERSE = {
 'prod': ('https://dataverse.nl',      '7cfc5b8f-3c8d-4c50-8bd5-2a56ad1ef51b'),
 'demo': ('https://demo.dataverse.nl', '5bf24ffd-1789-480f-b8a2-4ee18a9b895a')
}

base_url, api_token = DATAVERSE['prod']
headers = {'X-Dataverse-key':api_token }
dvid = 'UMCU' # '105754' # 'UMCU'
dataverse_view = f"{base_url}/api/dataverses/{dvid}"
dataverse_contents = f"{base_url}/api/dataverses/{dvid}/contents"
dataverse_roles = f"{base_url}/api/dataverses/{dvid}/assignments"
dataverse_groups = f"{base_url}/api/dataverses/{dvid}/groups"

response = requests.get(dataverse_groups, headers=headers)
print(response.json()['data']) 