#!/usr/bin/env python3

import json, argparse
from string import Template
from dave import Api, read_file, terms, read_file_json

parser = argparse.ArgumentParser()
parser.add_argument('--production', help='production', action='store')
args = parser.parse_args()
config = read_file_json('~/.config/dataverse.json')
if args.production:
    api = Api(config['production']['url'], config['production']['key'])
else:
    api = Api(config['demo']['url'], config['demo']['key'])

"""The metadata should be in a dictionary based on a JSON file with the minimum required
metadata, `dataset-minimal-metadata.json` (see Dataverse API documentation).

The contents of this file is a template string with replacement fields:
$title $authorname $authoraffiliation $contactemail $contactname $description.
The replacements are in the dict variable `props`.

To this metadata dictionary we add the Terms settings, of which there are 4 types."""

template = read_file('dataset-minimal-metadata.json')
props = {
    'title': "Test dataset 2", 'authorname': "Test author", 'authoraffiliation': "UMCU",
    'contactemail': 'dac@umcutrecht.nl', 'contactname': "Test author",
    'description': "Dataset created via API, including terms"
}
metadata = json.loads(Template(template).substitute(props))
metadata['datasetVersion'].update(terms['type_1'])
result = api.dataset_create(dataverse_id='45', props=metadata)
print(json.dumps(result, sort_keys=True, indent=2))
